# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfIhXjH4sGwLhSXrBwQus6NZ04EgZ66_
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([1, 1, 2, 3, 4, 5, 6])
mycolor = ['red', 'black', 'green', 'purple', 'lime', 'aqua', 'orange']
size = [20, 30, 40, 80, 100, 260, 500]

plt.scatter(x, y, c=mycolor, s=size)
plt.xlabel("X o'qi")
plt.ylabel("Y o'qi")
plt.title("Rangli nuqtalar")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(['510','613','614'])
y = np.array([18,20,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt

house_x = [1, 1, 3, 3, 1]
house_y = [1, 2, 2, 1, 1]

x = [1, 2, 3, 1]
y = [2, 3, 2, 2]

plt.plot(house_x, house_y, color='black')
plt.fill(house_x, house_y, color='grey', alpha=0.1)
plt.plot(roof_x, roof_y, color='black')
plt.fill(roof_x, roof_y, color='green', alpha=0.1)

plt.axis('equal')
plt.title("uy chizmasi")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([10, 30, 50, 10])
mylabels = ["1", "2", "3", "4"]

plt.pie(y, labels=mylabels,)  # autopct='%1.1f%%'
plt.title("Pie diagramma")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([10, 30, 50, 10])
mylabels = ["1", "2", "3", "4"]
plt.pie(y, labels=mylabels,startangle=90,explode=myexplode)
myexplode = [0.3,0,0,0]
plt.title("Pie diagramma")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([10, 30, 50, 10])
mylabels = ["1", "2", "3", "4"]
plt.pie(y, labels=mylabels,startangle=90,explode=myexplode)
myexplode = [0.3,0,0,0]
plt.title("Pie diagramma")
plt.legend(title='Fruits:')
plt.show()